// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbwZMW2Nck1tlM9oN-gR4f8nC6G81a2SE',
    appId: '1:86221482868:web:8a405e3a04dd448cd85a21',
    messagingSenderId: '86221482868',
    projectId: 'loginrs-fa856',
    authDomain: 'loginrs-fa856.firebaseapp.com',
    storageBucket: 'loginrs-fa856.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpcFpuF8jwtgweCbRjPhC7SPZFCTZDn2M',
    appId: '1:86221482868:android:0060105ab3cdfdccd85a21',
    messagingSenderId: '86221482868',
    projectId: 'loginrs-fa856',
    storageBucket: 'loginrs-fa856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4rq4GUrNUvcyERn6LmZqlh04xLHr05TU',
    appId: '1:86221482868:ios:649d2cb899315739d85a21',
    messagingSenderId: '86221482868',
    projectId: 'loginrs-fa856',
    storageBucket: 'loginrs-fa856.appspot.com',
    iosClientId: '86221482868-qvj0hdtvn494fb0mgbqolrpeg1eird45.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4rq4GUrNUvcyERn6LmZqlh04xLHr05TU',
    appId: '1:86221482868:ios:2b6c8d049b56633dd85a21',
    messagingSenderId: '86221482868',
    projectId: 'loginrs-fa856',
    storageBucket: 'loginrs-fa856.appspot.com',
    iosClientId: '86221482868-5nu12bsjfps6jvi01v17kd4rarv2jppn.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
